baseURL: "lucpaluskiewicz.github.io"
title: Luc Paluskiewicz
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 2
        - name: Resume
          url: resume/
          weight: 3
        - name: Teaching
          url: teaching/
          weight: 4
    
params:
    description: "PhD candidate at Paris School of Economics, Collège de France and EHESS."
    author: Luc Paluskiewicz
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["workingpapers", "workinprogress", "teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
        enabled: true
        title: Luc Paluskiewicz
        Subtitle: |
            <p class="justified"> I am a PhD candidate in Economics at <a href="https://www.parisschoolofeconomics.eu/" class="custom-link"> Paris School of Economics (PSE)</a>, <a href="https://www.college-de-france.fr/fr" class="custom-link"> Collège de France</a> and <a href=" https://www.ehess.fr/fr." class="custom-link"> EHESS</a>. </p>
            <p class="justified"> My research interests are in Innovation Economics and Political Economy. I am supervised by <a href="https://www.philippeaghion.com/" class="custom-link"> Philippe Aghion</a>.  </p>
            During the academic 2025-2026 year, I will be co-organizing the <a href="https://www.parisschoolofeconomics.eu/evenements/brown-bag-economics-of-innovation-seminar/" class="custom-link"> Brown Bag Economics of Innovation Seminar </a>, which is a joint seminar between Collège de France and INSEAD. Feel free to contact me, <a href="https://www.parisschoolofeconomics.eu/personnes/raphael-wargon/" class="custom-link">Raphaël Wargon </a>, or <a href="https://www.parisschoolofeconomics.eu/personnes/milla-tarpola/" class="custom-link">Milla Tarpola</a>.     
        imageUrl: "photo1.png"
        imageTitle: Luc Paluskiewicz
        imageWidth: 160
        imageHeight: 160
        buttons:
            - name: Research
              url: research/
            - name: Resume
              url: resume/
            - name: Teaching
              url: teaching/

    socialIcons:
        - name: cv
          url: CV_2025.pdf
        - name: Email
          url: mailto:luc.paluskiewicz@psemail.eu

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
        text: "Luc Paluskiewicz"
        icon: favicon.ico
        iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
